"""Create LangGraph store

Revision ID: e2a0c10ab218
Revises: 10414f3fd0c9
Create Date: 2024-10-19 01:30:41.486538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a0c10ab218'
down_revision: Union[str, None] = '10414f3fd0c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('langgraphs',
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('workflow', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('thread_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('langgraphs')
    # ### end Alembic commands ###
